#!/bin/bash
# Figure 10, INFless-KA bar. Usage: ./run_fig10_ka.sh <FUNC_NUM>
# Needs the trace generated by the Native run with the same FUNC_NUM.
# pipefail so that a crashing analyzer is not hidden behind tee.
set -u -o pipefail
cd "$(dirname "$0")"
source ../common/env.sh
FUNC_NUM=${1:?Usage: $0 <FUNC_NUM>}
MINUTES=5
mkdir -p logs_fig10
source ../common/kill_stale.sh
source ../common/ports.sh

TRACE="../../tools/req_arrivals_${FUNC_NUM}_${MINUTES}min_trace.npy"
if [ ! -f "$TRACE" ]; then
    echo "ERROR: $TRACE missing. Run ./run_fig10_native.sh $FUNC_NUM first."
    exit 1
fi

cleanup() {
    echo "[cleanup] stopping keepalive processes..."
    kill_stale_processes
    rm -rf /dev/shm/ipc
    [ -f ka.log ]       && cp ka.log       "logs_fig10/ka_${FUNC_NUM}_${MINUTES}min.log"
    [ -f baseline.log ] && cp baseline.log "logs_fig10/ka_${FUNC_NUM}_${MINUTES}min_baseline.log"
    PROC_DIR="logs_fig10/ka_${FUNC_NUM}_${MINUTES}min_proc"
    for f in log_client_*.txt log_executor_*.txt log_cuda_server*.txt router_stdout.log; do
        [ -e "$f" ] || continue
        mkdir -p "$PROC_DIR" && mv "$f" "$PROC_DIR/"
    done
}
trap cleanup EXIT

kill_stale_processes
rm -rf /dev/shm/ipc && mkdir -p /dev/shm/ipc

# Remove the previous run's logs first: if the driver dies at startup, the
# analyzer would otherwise report the previous run's results as this one's.
rm -f ka.log router.log baseline.log
rm -f "logs_fig10/ka_${FUNC_NUM}_result.txt"
rm -f log_client_*.txt log_executor_*.txt log_cuda_server*.txt router_stdout.log

# 1. Derive per-function keep-alive values from the shared trace
( cd ../../tools/ && python3 export_keepalive.py "req_arrivals_${FUNC_NUM}_${MINUTES}min_trace.npy" ) \
    || { echo "export_keepalive failed"; exit 1; }
sleep 2

# 2. Keep-alive router.
# Pinned to a core outside all NUMA_CORES ranges so the clients cannot starve it.
nohup taskset -c 200 python3 baseline_keepalive.py -m resnet152 -s 4 -f "$FUNC_NUM" > baseline.log 2>&1 &
sleep 10

# 3. Wait for the initially resident endpoints (at most 72 = 4 x 18)
if [ "$FUNC_NUM" -gt 72 ]; then CHECK_LIMIT=72; else CHECK_LIMIT=$FUNC_NUM; fi
echo "Waiting for $CHECK_LIMIT keepalive endpoints..."
for ((i=0; i<CHECK_LIMIT; i++)); do
    PORT=$((CLIENT_PORT_BASE + i))
    COUNT=0
    until curl -s "http://localhost:$PORT" > /dev/null; do
        sleep 1
        COUNT=$((COUNT + 1))
        if [ $COUNT -ge 180 ]; then
            echo "Warning: endpoint $PORT not ready after 180s, skipping..."
            break
        fi
    done
done
echo "Endpoints up (or timed out). Settling..."
sleep 5

# 4. Replay the same trace
python3 sender_from_trace.py "$FUNC_NUM" "$MINUTES" 0 || { echo "sender failed"; exit 1; }
sleep 10

# 5. Analyze
python3 figure10_analyze_router_log.py ka.log --total_func "$FUNC_NUM" \
    | tee "logs_fig10/ka_${FUNC_NUM}_result.txt"
